config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/avis', to: 'messages#affichage'
  get '/admin', to: 'admins#index'
  delete '/admin/delete', to: 'admins#delete'
  post '/admin/update', to: 'admins#update'

  root "messages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/header.rb
class Header < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  validates :text, presence: true , length: { maximum: 30 }
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

  def index
  end

  def delete
    @messages = Message.all
    @messages.destroy_all
    render 'index'
  end

  def update
    @header = Header.find_by_id(1)
    @header.update(header_params)
    redirect_to root_path
  end

  private
      def header_params
        params.require(:header).permit(:title)
      end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @header = Header.find_by_id(1)
  end

  def affichage
    @messages = Message.all
    @list_message = []
    @messages.each_with_index  do |message, index|
      text_message = message.text
      size_message = message.size
      hash_message = {text: text_message, size: size_message}
      @list_message << hash_message
    end
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/admins/index.html.erb
<div class="container">
	<h1>Admin panel</h1>
	<button type="button" name="button"><%= link_to 'Delete database', admin_delete_path,
										              method: :delete,
										              data: { confirm: 'Are you sure?' }, id: 'delete-database-button' %></button>


	<h3>modification du header</h3>
	<%= form_for :header , url: admin_update_path do |f| %>
	  <p>
	    <%= f.label :title %><br>
	    <%= f.text_area :title %>
	  </p>
	  <p>
	    <%= f.submit %>
	  </p>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vote</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/affichage.html.erb
<div class="container-fluid">

  <div class="row">
    <div class="col-md-2 .col-sm-2 col-xs-1"> </div>
    <div class="col-md-8 .col-sm-8 col-xs-10">
      <div id="word-alone"></div>
      <div id="word-cloud"></div>
    </div>
    <div class="col-md-2 .col-sm-2 col-xs-1"></div>
  </div>
  <div class="row" id="messagehash">
    <%= @list_message.to_json %>
  </div>

</div>

app/views/messages/index.html.erb
<div class="container-fluid" id="grad">

  <div class="row">
    <div class="col-md-2 .col-sm-2 col-xs-1"> </div>
    <div class="col-md-8 .col-sm-8 col-xs-10">
      <!-- <div class="text-zone"><h2 id = "title"><%= @header.title %></h2></div> -->
      <div class="text-zone"><h2 id = "title">Les 40 ans de Sandrine</h2></div>
    </div>
    <div class="col-md-2 .col-sm-2 col-xs-1"> </div>
  </div>

  <div class="row">
    <div class="col-md-2 .col-sm-2 col-xs-1"> </div>
    <div class="col-md-8 .col-sm-8 col-xs-10">
      <div class="text-zone">
        <textarea id="message" placeholder="Ecrivez un mot pour Sandrine puis appuyez sur entrée ou clickez ok"></textarea>
        <button id="okbutton" class="btn btn-default">OK</button>
      </div>
    </div>
    <div class="col-md-2 .col-sm-2 col-xs-1"> </div>
  </div>

  <div class="row fond">
    <div class="col-md-2 .col-sm-2 col-xs-1"> </div>
    <div class="col-md-8 .col-sm-8 col-xs-10">
      <button class="btn btn-primary" id="buttoncloud"><%= link_to "Voir le nuage", avis_path, id: "cloudlink" , target: :_blank%></button>
    </div>
    <div class="col-md-2 .col-sm-2 col-xs-1"> </div>
  </div>

  <div class="row">
    <div class="col-md-12 .col-sm-12 col-xs-12" id = "error_message">
    </div>
  </div>

</div>